### ISSUE TITLE
Don't override default compilation-buffer-name

### ISSUE THREAD

**Issue by NJBS** [hasky-mode/hasky-stack#3]
I was wondering if it would be possible to [not override the default compilation-buffer-name](https://github.com/hasky-mode/hasky-stack/blob/bbbe58bf11f0188dfc71d3786a1bef73b9650fba/hasky-stack.el#L327-L335), overriding the default `*compilation*` prevents packages like [popwin](https://github.com/m2ym/popwin-el) from catching the stack compilation buffer by default.

If you feel strongly about keeping the current naming scheme, I could submit a PR to make it opt-in via a configuration variable.

Great package by the way, really loving it!

**Comment by mrkkrp** [comment]
I think if we use the same name for all compilation processes it'll be

1. Confusing. I often want to visit e.g. `*my-project-stack*` buffer and when it's named after corresponding project it's easy to find it.

2. It'll be impossible to have a command running for one project and another command running for a different project because there may be only one compilation process with a given name.

----

I think perhaps it's a flaw in the `popwin` package. Is it possible to make it catch compilation buffers by detecting that they are in `compilation-mode`? This would make a lot more sense than demanding that all compilation buffers use the same name, IMO.

**Comment by NJBS** [comment]
Indeed, that's fair. I'm not often compiling two stack projects at the same time so I didn't consider your first two points.

> I think perhaps it's a flaw in the popwin package. Is it possible to make it catch compilation buffers by detecting that they are in compilation-mode? This would make a lot more sense than demanding that all compilation buffers use the same name, IMO.

Yes, however many packages abuse `compile` so catching all `compilation-mode` buffers has caused some issues for me in the past.

For now I'll just add a regexp to catch any *-stack buffers.

Thanks for the quick response!
